

about :

  name : "wMathSpace"
  description : "Collection of functions for matrix math. MathSpace introduces class Space which is a multidimensional structure which in the most trivial case is Matrix of scalars. A matrix of specific form could also be classified as a vector. MathSpace heavily relly on MathVector, which introduces VectorImage. VectorImage is a reference, it does not contain data but only refer on actual ( aka Long ) container of lined data.  Use MathSpace for arithmetic operations with matrices, to triangulate, permutate or transform matrix, to get a specific or the general solution of a system of linear equations, to get LU, QR decomposition, for SVD or PCA. Also, Space is a convenient and efficient data container, you may use it to continuously store huge an array of arrays or for matrix computation."
  version : "0.3.79"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wMathSpace.git
  bugs : https://github.com/Wandalen/wMathSpace/issues

step :

  export.proto :
    inherit : predefined.export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

